///************************************************
/// Generated by: TuyenNT
/// Date: 24/05/2015 09:42:37
/// Goal: Create Form for IMPORT_EXCEL_HANG_HOA
///************************************************


using System;
using System.Data;
using System.Drawing;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;

using IP.Core.IPCommon;
using IP.Core.IPException;
using IP.Core.IPData;
using IP.Core.IPUserService;
using IP.Core.IPSystemAdmin;

using BKI_KHO.US;
using BKI_KHO.DS;
using BKI_KHO.DS.CDBNames;

using C1.Win.C1FlexGrid;
using IP.Core.IPExcelReport;

namespace BKI_KHO
{



	public class frm_import_excel_hang_hoa : System.Windows.Forms.Form {
		internal System.Windows.Forms.Panel m_pnl_out_place_dm;
        private C1.Win.C1FlexGrid.C1FlexGrid m_fg;
        private Panel panel1;
        internal ImageList imageList1;
        private ComboBox m_cbo_nhom_hang;
        private Label label2;
        private TextBox m_txt_ma_ct;
        private Label m_lbl_ma_chung_tu;
        private DateTimePicker m_dat_ngay_nhap_thuc_te;
        private Label m_lbl_ngay_nhap_thuc_te;
        private Label m_lbl_loading_mes;
        private OpenFileDialog m_ofd_exel_file;
        private DevExpress.XtraEditors.SimpleButton m_cmd_chon_file_excel;
        private DevExpress.XtraEditors.SimpleButton m_cmd_save_data;
		private System.ComponentModel.IContainer components;

		public frm_import_excel_hang_hoa()
		{
			//
			// Required for Windows Form Designer support
			//
			InitializeComponent();

			//
			// TODO: Add any constructor code after InitializeComponent call
			//
			format_controls();
		}

		/// <summary>
		/// Clean up any resources being used.
		/// </summary>
		protected override void Dispose( bool disposing )
		{
			if( disposing )
			{
				if(components != null)
				{
					components.Dispose();
				}
			}
			base.Dispose( disposing );
		}

		#region Windows Form Designer generated code
		/// <summary>
		/// Required method for Designer support - do not modify
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frm_import_excel_hang_hoa));
            this.m_pnl_out_place_dm = new System.Windows.Forms.Panel();
            this.m_cmd_save_data = new DevExpress.XtraEditors.SimpleButton();
            this.m_cmd_chon_file_excel = new DevExpress.XtraEditors.SimpleButton();
            this.m_fg = new C1.Win.C1FlexGrid.C1FlexGrid();
            this.panel1 = new System.Windows.Forms.Panel();
            this.m_cbo_nhom_hang = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.m_txt_ma_ct = new System.Windows.Forms.TextBox();
            this.m_lbl_ma_chung_tu = new System.Windows.Forms.Label();
            this.m_dat_ngay_nhap_thuc_te = new System.Windows.Forms.DateTimePicker();
            this.m_lbl_ngay_nhap_thuc_te = new System.Windows.Forms.Label();
            this.imageList1 = new System.Windows.Forms.ImageList(this.components);
            this.m_lbl_loading_mes = new System.Windows.Forms.Label();
            this.m_ofd_exel_file = new System.Windows.Forms.OpenFileDialog();
            this.m_pnl_out_place_dm.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).BeginInit();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // m_pnl_out_place_dm
            // 
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_save_data);
            this.m_pnl_out_place_dm.Controls.Add(this.m_cmd_chon_file_excel);
            this.m_pnl_out_place_dm.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.m_pnl_out_place_dm.Location = new System.Drawing.Point(0, 367);
            this.m_pnl_out_place_dm.Name = "m_pnl_out_place_dm";
            this.m_pnl_out_place_dm.Padding = new System.Windows.Forms.Padding(4);
            this.m_pnl_out_place_dm.Size = new System.Drawing.Size(686, 42);
            this.m_pnl_out_place_dm.TabIndex = 19;
            // 
            // m_cmd_save_data
            // 
            this.m_cmd_save_data.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_save_data.Image = ((System.Drawing.Image)(resources.GetObject("m_cmd_save_data.Image")));
            this.m_cmd_save_data.Location = new System.Drawing.Point(137, 4);
            this.m_cmd_save_data.Name = "m_cmd_save_data";
            this.m_cmd_save_data.Size = new System.Drawing.Size(128, 34);
            this.m_cmd_save_data.TabIndex = 43;
            this.m_cmd_save_data.Text = "Lưu hàng hóa";
            // 
            // m_cmd_chon_file_excel
            // 
            this.m_cmd_chon_file_excel.Dock = System.Windows.Forms.DockStyle.Left;
            this.m_cmd_chon_file_excel.Image = ((System.Drawing.Image)(resources.GetObject("m_cmd_chon_file_excel.Image")));
            this.m_cmd_chon_file_excel.Location = new System.Drawing.Point(4, 4);
            this.m_cmd_chon_file_excel.Name = "m_cmd_chon_file_excel";
            this.m_cmd_chon_file_excel.Size = new System.Drawing.Size(133, 34);
            this.m_cmd_chon_file_excel.TabIndex = 42;
            this.m_cmd_chon_file_excel.Text = "Chọn File Excel";
            // 
            // m_fg
            // 
            this.m_fg.ColumnInfo = resources.GetString("m_fg.ColumnInfo");
            this.m_fg.Dock = System.Windows.Forms.DockStyle.Fill;
            this.m_fg.Location = new System.Drawing.Point(0, 100);
            this.m_fg.Name = "m_fg";
            this.m_fg.Size = new System.Drawing.Size(686, 267);
            this.m_fg.Styles = new C1.Win.C1FlexGrid.CellStyleCollection(resources.GetString("m_fg.Styles"));
            this.m_fg.TabIndex = 20;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.m_cbo_nhom_hang);
            this.panel1.Controls.Add(this.label2);
            this.panel1.Controls.Add(this.m_txt_ma_ct);
            this.panel1.Controls.Add(this.m_lbl_ma_chung_tu);
            this.panel1.Controls.Add(this.m_dat_ngay_nhap_thuc_te);
            this.panel1.Controls.Add(this.m_lbl_ngay_nhap_thuc_te);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(686, 100);
            this.panel1.TabIndex = 21;
            // 
            // m_cbo_nhom_hang
            // 
            this.m_cbo_nhom_hang.FormattingEnabled = true;
            this.m_cbo_nhom_hang.Location = new System.Drawing.Point(134, 68);
            this.m_cbo_nhom_hang.Name = "m_cbo_nhom_hang";
            this.m_cbo_nhom_hang.Size = new System.Drawing.Size(200, 21);
            this.m_cbo_nhom_hang.TabIndex = 11;
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(9, 71);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(110, 13);
            this.label2.TabIndex = 10;
            this.label2.Text = "Nhập vào nhóm hàng";
            // 
            // m_txt_ma_ct
            // 
            this.m_txt_ma_ct.Location = new System.Drawing.Point(134, 36);
            this.m_txt_ma_ct.Name = "m_txt_ma_ct";
            this.m_txt_ma_ct.Size = new System.Drawing.Size(200, 20);
            this.m_txt_ma_ct.TabIndex = 8;
            this.m_txt_ma_ct.Text = "SDD-";
            // 
            // m_lbl_ma_chung_tu
            // 
            this.m_lbl_ma_chung_tu.AutoSize = true;
            this.m_lbl_ma_chung_tu.Location = new System.Drawing.Point(9, 39);
            this.m_lbl_ma_chung_tu.Name = "m_lbl_ma_chung_tu";
            this.m_lbl_ma_chung_tu.Size = new System.Drawing.Size(65, 13);
            this.m_lbl_ma_chung_tu.TabIndex = 9;
            this.m_lbl_ma_chung_tu.Text = "Số chứng từ";
            // 
            // m_dat_ngay_nhap_thuc_te
            // 
            this.m_dat_ngay_nhap_thuc_te.CustomFormat = "dd/MM/yyyy";
            this.m_dat_ngay_nhap_thuc_te.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.m_dat_ngay_nhap_thuc_te.Location = new System.Drawing.Point(134, 10);
            this.m_dat_ngay_nhap_thuc_te.Name = "m_dat_ngay_nhap_thuc_te";
            this.m_dat_ngay_nhap_thuc_te.Size = new System.Drawing.Size(200, 20);
            this.m_dat_ngay_nhap_thuc_te.TabIndex = 6;
            this.m_dat_ngay_nhap_thuc_te.Value = new System.DateTime(2014, 5, 7, 14, 52, 0, 0);
            // 
            // m_lbl_ngay_nhap_thuc_te
            // 
            this.m_lbl_ngay_nhap_thuc_te.AutoSize = true;
            this.m_lbl_ngay_nhap_thuc_te.Location = new System.Drawing.Point(9, 16);
            this.m_lbl_ngay_nhap_thuc_te.Name = "m_lbl_ngay_nhap_thuc_te";
            this.m_lbl_ngay_nhap_thuc_te.Size = new System.Drawing.Size(62, 13);
            this.m_lbl_ngay_nhap_thuc_te.TabIndex = 7;
            this.m_lbl_ngay_nhap_thuc_te.Text = "Ngày nhập ";
            // 
            // imageList1
            // 
            this.imageList1.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("imageList1.ImageStream")));
            this.imageList1.TransparentColor = System.Drawing.Color.Transparent;
            this.imageList1.Images.SetKeyName(0, "");
            this.imageList1.Images.SetKeyName(1, "");
            this.imageList1.Images.SetKeyName(2, "About.png");
            this.imageList1.Images.SetKeyName(3, "Application.png");
            this.imageList1.Images.SetKeyName(4, "Back.png");
            this.imageList1.Images.SetKeyName(5, "Bottom.png");
            this.imageList1.Images.SetKeyName(6, "Create.png");
            this.imageList1.Images.SetKeyName(7, "Delete.png");
            this.imageList1.Images.SetKeyName(8, "Download.png");
            this.imageList1.Images.SetKeyName(9, "Exit.png");
            this.imageList1.Images.SetKeyName(10, "Find.png");
            this.imageList1.Images.SetKeyName(11, "First.png");
            this.imageList1.Images.SetKeyName(12, "Go back.png");
            this.imageList1.Images.SetKeyName(13, "Go forward.png");
            this.imageList1.Images.SetKeyName(14, "Go.png");
            this.imageList1.Images.SetKeyName(15, "List.png");
            this.imageList1.Images.SetKeyName(16, "Modify.png");
            this.imageList1.Images.SetKeyName(17, "No-entry.png");
            this.imageList1.Images.SetKeyName(18, "Repair.png");
            this.imageList1.Images.SetKeyName(19, "Report.png");
            this.imageList1.Images.SetKeyName(20, "Save.png");
            this.imageList1.Images.SetKeyName(21, "Yes.png");
            this.imageList1.Images.SetKeyName(22, "excel.ico");
            // 
            // m_lbl_loading_mes
            // 
            this.m_lbl_loading_mes.BackColor = System.Drawing.SystemColors.ControlLightLight;
            this.m_lbl_loading_mes.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.m_lbl_loading_mes.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.m_lbl_loading_mes.Location = new System.Drawing.Point(134, 172);
            this.m_lbl_loading_mes.Name = "m_lbl_loading_mes";
            this.m_lbl_loading_mes.Size = new System.Drawing.Size(301, 68);
            this.m_lbl_loading_mes.TabIndex = 27;
            this.m_lbl_loading_mes.Text = "Vui lòng đợi trong giây lát ...";
            this.m_lbl_loading_mes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.m_lbl_loading_mes.Visible = false;
            // 
            // m_ofd_exel_file
            // 
            this.m_ofd_exel_file.FileName = "openFileDialog1";
            // 
            // frm_import_excel_hang_hoa
            // 
            this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.ClientSize = new System.Drawing.Size(686, 409);
            this.Controls.Add(this.m_lbl_loading_mes);
            this.Controls.Add(this.m_fg);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.m_pnl_out_place_dm);
            this.Name = "frm_import_excel_hang_hoa";
            this.Text = "Nhập số dư đầu";
            this.Load += new System.EventHandler(this.frm_import_excel_hang_hoa_Load);
            this.m_pnl_out_place_dm.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.m_fg)).EndInit();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);

		}
		#endregion

		#region Public Interface
		public void display(){			
			this.ShowDialog();
		}
		#endregion

		#region Data Structure
		private enum e_col_Number{
			GIA_NHAP = 4
,MA_HANG = 2
,STT = 1
,TEN_HANG = 3
            ,GIA_BAN = 5
		}			
		#endregion

		#region Members
		ITransferDataRow m_obj_trans;		
		DS_IMPORT_EXCEL_HANG_HOA m_ds = new DS_IMPORT_EXCEL_HANG_HOA();
		US_IMPORT_EXCEL_HANG_HOA m_us = new US_IMPORT_EXCEL_HANG_HOA();
		#endregion

		#region Private Methods
		private void format_controls(){
			CControlFormat.setFormStyle(this, new CAppContext_201());
			CControlFormat.setC1FlexFormat(m_fg);
			CGridUtils.AddSave_Excel_Handlers(m_fg);
            			CGridUtils.AddSearch_Handlers(m_fg);
			set_define_events();
			this.KeyPreview = true;		
		}
        private void load_data_cbo_nhom_hang() {
            DS_DM_NHOM_HANG v_ds = new DS_DM_NHOM_HANG();
            US_DM_NHOM_HANG v_us = new US_DM_NHOM_HANG();
            v_ds.Clear();
            v_ds.EnforceConstraints = false;

            v_us.FillDataset(v_ds, "where level_mode = 1");
            m_cbo_nhom_hang.DataSource = v_ds.DM_NHOM_HANG;
            m_cbo_nhom_hang.ValueMember = DM_NHOM_HANG.ID;
            m_cbo_nhom_hang.DisplayMember = DM_NHOM_HANG.TEN;
        }
		private void set_initial_form_load(){
            m_dat_ngay_nhap_thuc_te.Value = DateTime.Now.Date;	
			m_obj_trans = get_trans_object(m_fg);
            load_data_cbo_nhom_hang();
			load_data_2_grid();		
		}	
		private ITransferDataRow get_trans_object(C1.Win.C1FlexGrid.C1FlexGrid i_fg){
			Hashtable v_htb = new Hashtable();
			v_htb.Add(IMPORT_EXCEL_HANG_HOA.GIA_NHAP, e_col_Number.GIA_NHAP);
			v_htb.Add(IMPORT_EXCEL_HANG_HOA.MA_HANG, e_col_Number.MA_HANG);
			v_htb.Add(IMPORT_EXCEL_HANG_HOA.STT, e_col_Number.STT);
			v_htb.Add(IMPORT_EXCEL_HANG_HOA.TEN_HANG, e_col_Number.TEN_HANG);
            v_htb.Add(IMPORT_EXCEL_HANG_HOA.GIA_BAN, e_col_Number.GIA_BAN);					
			ITransferDataRow v_obj_trans = new CC1TransferDataRow(i_fg,v_htb,m_ds.IMPORT_EXCEL_HANG_HOA.NewRow());
			return v_obj_trans;			
		}
		private void load_data_2_grid(){						
			m_ds = new DS_IMPORT_EXCEL_HANG_HOA();			
			m_us.FillDataset(m_ds);
			m_fg.Redraw = false;
			CGridUtils.Dataset2C1Grid(m_ds, m_fg, m_obj_trans);
			m_fg.Redraw = true;
		}
		private void grid2us_object(US_IMPORT_EXCEL_HANG_HOA i_us
			, int i_grid_row) {
			DataRow v_dr;
			v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			m_obj_trans.GridRow2DataRow(i_grid_row,v_dr);
			i_us.DataRow2Me(v_dr);
		}

	
		private void us_object2grid(US_IMPORT_EXCEL_HANG_HOA i_us
			, int i_grid_row) {
			DataRow v_dr = (DataRow) m_fg.Rows[i_grid_row].UserData;
			i_us.Me2DataRow(v_dr);
			m_obj_trans.DataRow2GridRow(v_dr, i_grid_row);
		}


		private void insert_import_excel_hang_hoa(){			
		//	frm_import_excel_hang_hoa_DE v_fDE = new  frm_import_excel_hang_hoa_DE();								
		//	v_fDE.display();
			load_data_2_grid();
		}

		private void update_import_excel_hang_hoa(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;			
			grid2us_object(m_us, m_fg.Row);
		//	frm_import_excel_hang_hoa_DE v_fDE = new frm_import_excel_hang_hoa_DE();
		//	v_fDE.display(m_us);
			load_data_2_grid();
		}
				
		private void delete_import_excel_hang_hoa(){
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			if (BaseMessages.askUser_DataCouldBeDeleted(8) != BaseMessages.IsDataCouldBeDeleted.CouldBeDeleted)  return;
			US_IMPORT_EXCEL_HANG_HOA v_us = new US_IMPORT_EXCEL_HANG_HOA();
			grid2us_object(v_us, m_fg.Row);
			try {			
				v_us.BeginTransaction();    											
				v_us.Delete();                      								
				v_us.CommitTransaction();
				m_fg.Rows.Remove(m_fg.Row);				
			}
			catch (Exception v_e) {
				v_us.Rollback();
				CDBExceptionHandler v_objErrHandler = new CDBExceptionHandler(v_e,
					new CDBClientDBExceptionInterpret());
				v_objErrHandler.showErrorMessage();
			}
		}

		private void view_import_excel_hang_hoa(){			
			if (!CGridUtils.IsThere_Any_NonFixed_Row(m_fg)) return;
			if (!CGridUtils.isValid_NonFixed_RowIndex(m_fg, m_fg.Row)) return;
			grid2us_object(m_us, m_fg.Row);
		//	frm_import_excel_hang_hoa_DE v_fDE = new frm_import_excel_hang_hoa_DE();			
		//	v_fDE.display(m_us);
		}

        private void load_file_excel() {
            if(m_ofd_exel_file.ShowDialog() == System.Windows.Forms.DialogResult.OK) {
                try {
                    // Reset lại ds mới nếu chọn lại file excel khác

                    //m_ds.Clear();
                    //m_ds = new DS_EXCEL_IMPORT_HOC_VIEN();
                    DS_IMPORT_EXCEL_HANG_HOA v_ds = new DS_IMPORT_EXCEL_HANG_HOA();
                    v_ds.Clear();
                    v_ds.EnforceConstraints = false;

                    m_lbl_loading_mes.Visible = true;
                    CExcelReport v_excel_rpt = new CExcelReport(m_ofd_exel_file.FileName);

                    m_ds.EnforceConstraints = false;
                    v_excel_rpt.Export2DatasetDS_by_DucVT(v_ds, v_ds.IMPORT_EXCEL_HANG_HOA.TableName, 6);

                    m_fg.Redraw = false;

                    //Gán DataSource
                    //m_fg.DataSource = m_ds.DM_NHAN_SU;

                    CGridUtils.Dataset2C1Grid(v_ds, m_fg, m_obj_trans);
                    m_fg.Redraw = true;
                    m_lbl_loading_mes.Visible = false;

                }
                catch(Exception v_e) {
                    CSystemLog_301.ExceptionHandle(v_e);
                }
            }
        }

        private void form_2_us_v_gd_chung_tu(US_GD_CHUNG_TU ip_us_gd_chung_tu) {

            ip_us_gd_chung_tu.dcID_LOAI_CT = CONST_ID_DM_LOAI_CHUNG_TU.ID_NHAP_SO_DU;
            ip_us_gd_chung_tu.strDIEN_GIAI = "Nhập sô dư đầu hàng hóa cho kho";
            ip_us_gd_chung_tu.strMA_CT = m_txt_ma_ct.Text;

            ip_us_gd_chung_tu.SetID_TO_CHUC_DICHNull();
            ip_us_gd_chung_tu.SetID_TO_CHUC_NGUONNull();
            ip_us_gd_chung_tu.SetID_NGUOI_GIAO_DICHNull();

            ip_us_gd_chung_tu.SetGHI_CHU_1Null();
            ip_us_gd_chung_tu.SetGHI_CHU_2Null();
            ip_us_gd_chung_tu.SetGHI_CHU_3Null();

            ip_us_gd_chung_tu.dcID_NGUOI_NHAP = CAppContext_201.getCurrentUserID();
            ip_us_gd_chung_tu.datNGAY_CT = IP.Core.IPSystemAdmin.CAppContext_201.getCurentDate();
            ip_us_gd_chung_tu.datNGAY_NHAP = IP.Core.IPSystemAdmin.CAppContext_201.getCurentDate();
            ip_us_gd_chung_tu.datNGAY_NHAP_CUOI = IP.Core.IPSystemAdmin.CAppContext_201.getCurentDate();
        }
        private void grid_row_2_us_gd_chi_tiet_chung_tu(
            int ip_grid_row
            , US_V_GD_CHI_TIET_CHUNG_TU iop_us_gd_chi_tiet_chung_tu
            , US_GD_CHUNG_TU ip_us_gd_chung_tu) {

            iop_us_gd_chi_tiet_chung_tu.dcID_CHUNG_TU
                = ip_us_gd_chung_tu.dcID;

            iop_us_gd_chi_tiet_chung_tu.SetMA_CTNull();                 //NULL
            iop_us_gd_chi_tiet_chung_tu.SetNGAY_CTNull();               //NULL
            iop_us_gd_chi_tiet_chung_tu.SetDIEN_GIAINull();             //NULL
            iop_us_gd_chi_tiet_chung_tu.SetTONG_TIENNull();             //NULL
            iop_us_gd_chi_tiet_chung_tu.SetID_TO_CHUC_NGUONNull();      //NULL
            iop_us_gd_chi_tiet_chung_tu.SetID_NGUOI_GIAO_DICHNull();    //NULL
            iop_us_gd_chi_tiet_chung_tu.SetID_NGUOI_NHAPNull();         //NULL
            iop_us_gd_chi_tiet_chung_tu.SetNGAY_NHAP_PMNull();          //NULL

            iop_us_gd_chi_tiet_chung_tu.dcID_NHOM
                = CIPConvert.ToDecimal(m_cbo_nhom_hang.SelectedValue);

            iop_us_gd_chi_tiet_chung_tu.strMA_HANG
                = CIPConvert.ToStr(m_fg[ip_grid_row, (int)e_col_Number.MA_HANG]);

            iop_us_gd_chi_tiet_chung_tu.strTEN_HANG_VN
                = CIPConvert.ToStr(m_fg[ip_grid_row, (int)e_col_Number.TEN_HANG]);

            iop_us_gd_chi_tiet_chung_tu.dcGiA_NHAP
                = CIPConvert.ToDecimal(m_fg[ip_grid_row, (int)e_col_Number.GIA_NHAP]);

            iop_us_gd_chi_tiet_chung_tu.dcID_TRANG_THAI = CONST_ID_TRANG_THAI_HANG_HOA.ID_DA_NHAP;


            iop_us_gd_chi_tiet_chung_tu.dcSO_LUONG = 1;

            iop_us_gd_chi_tiet_chung_tu.SetTEN_LOAI_CTNull();
            iop_us_gd_chi_tiet_chung_tu.dcID_DVT_THOI_GIAN = CONST_ID_DVT_THOI_GIAN.ID_THANG;
            iop_us_gd_chi_tiet_chung_tu.dcGIA_BAN = CIPConvert.ToDecimal(m_fg[ip_grid_row, (int)e_col_Number.GIA_BAN]);
        }
        private void save_data() {
            //1. Kiem tra du lieu da ok chua? Neu chua OK thi khong lam gi het!
            if(!check_validate_is_ok())
                return;

            US_GD_CHUNG_TU v_us_gd_chung_tu = new US_GD_CHUNG_TU();
            US_V_GD_CHI_TIET_CHUNG_TU v_us_gd_chi_tiet_chung_tu = new US_V_GD_CHI_TIET_CHUNG_TU();

            try {

                v_us_gd_chung_tu.BeginTransaction();
                //2. insert data
                //2.1 insert chung tu
                form_2_us_v_gd_chung_tu(v_us_gd_chung_tu);
                v_us_gd_chung_tu.Insert();
                v_us_gd_chi_tiet_chung_tu.UseTransOfUSObject(v_us_gd_chung_tu);
                //2.2 insert hang hoa va gd chi tiet chung tu
                for(int v_i_cur_row = m_fg.Rows.Fixed; v_i_cur_row < m_fg.Rows.Count - 1; v_i_cur_row++) {
                    grid_row_2_us_gd_chi_tiet_chung_tu(v_i_cur_row, v_us_gd_chi_tiet_chung_tu, v_us_gd_chung_tu);
                    v_us_gd_chi_tiet_chung_tu.Insert();
                }
                v_us_gd_chung_tu.CommitTransaction();
            }
            catch(System.Exception v_e) {
                if(v_us_gd_chung_tu.is_having_transaction()) {
                    v_us_gd_chung_tu.Rollback();
                }
                throw v_e;
            }

            //3. Thong bao thanh cong
            BaseMessages.MsgBox_Infor("Bạn đã cập nhật xong số dư đầu cho hàng hóa!");
        }

        private bool check_validate_is_ok() {
            return true;
        }
		#endregion

//
		//
		//		EVENT HANLDERS
		//
		//
        private void set_define_events() {
            m_cmd_chon_file_excel.Click += m_cmd_chon_file_excel_Click;
            this.Load += frm_import_excel_hang_hoa_Load;
            m_cmd_save_data.Click += m_cmd_save_data_Click;
        }

        void m_cmd_save_data_Click(object sender, EventArgs e) {
            try {
                save_data();
            }
            catch(Exception v_e) {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }

        void m_cmd_chon_file_excel_Click(object sender, EventArgs e) {
            try {
                load_file_excel();
            }
            catch(Exception v_e) {
                CSystemLog_301.ExceptionHandle(v_e);
            }
        }
		private void frm_import_excel_hang_hoa_Load(object sender, System.EventArgs e) {
			try{
				set_initial_form_load();
			}
			catch (Exception v_e){
				CSystemLog_301.ExceptionHandle(v_e);
			}
		
		}

		
	}
}

